### ISSUE TITLE
Swapped error messages in BumpyMatrix.R

### ISSUE THREAD

**Issue by ChristopherEeles** [LTLA/BumpyMatrix#2]
Hi @LTLA,

I was reading your code and unless I am missing something it looks like your if statements and error messages should be swapped between the `rbind` and `cbind` methods for `BumpyMatrix`.

See lines 341-343 and 365-367 in https://github.com/LTLA/BumpyMatrix/blob/master/R/BumpyMatrix.R.

Best,
Christopher Eeles
Software Developer @ BHKLab
Princess Margaret Cancer Research Centre

**Comment by LTLA** [comment]
Yes, thanks for the spot.
