### ISSUE TITLE
Possiblity for SQL or HDF5 backed BumpyMatrices?

### ISSUE THREAD

**Issue by sa-lee** [LTLA/BumpyMatrix#4]
Hi Aaron, 

This package has been great to use so far, thanks for making it! One question - would it be possible to have a SQL database or an HDF5 file backed BumpyMatrix? Our use case is for shoving timeseries or AIRR data as BumpyMatrices into MAEs. 

Stuart

**Comment by LTLA** [comment]
I don't see why not. The `BumpyDataFrameMatrix` only requires a `CompressedSplitDataFrameList`, which in turn supports any `DataFrame` subclass beyond a fully in-memory `DFrame`. So if you make a HDF5- or SQL-backed `DataFrame` subclass, then you should be able to plug it into a CSDFL and from there into a BDFM.

I believe some aspects of a SQL-backed subclass already exists, see discussion at Bioconductor/SQLDataFrame#4. There may also be something you could do with a `DelayedDataFrame` but I don't have much experience with those.

**Comment by sa-lee** [comment]
It looks like you get a `CompressedSplitDataFrameList` from `DelayedDataFrame` so I'll have a play around with that. Thanks!
